version: '3.4'

services:
  wizardsofttest:
    image: wizardsofttest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - redis  

  redis:
    image: redis:alpine  
    ports:
      - "6379:6379"